// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqkjwojzdgtnvqkmvgfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxa2p3b2p6ZGd0bnZxa212Z2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTI2ODgsImV4cCI6MjA3NDk2ODY4OH0.LganWlR2Z_YMz7fW4EjJcrTsxAHmdd2C8_r8SCR2MeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});